x-health-check-config-default: &default-health-check
  timeout: 10s
  interval: 30s
  retries: 5
  start_period: 5s

x-backend-environment: &backend-environment
  ENVIRONMENT: ${ENVIRONMENT:?Variable is not set or empty}

  JWT_SECRET_KEY: ${JWT_SECRET_KEY:?Variable is not set or empty}
  JWT_ACCESS_TOKEN_EXPIRES: ${JWT_ACCESS_TOKEN_EXPIRES:?Variable is not set or empty}
  JWT_REFRESH_TOKEN_EXPIRES: ${JWT_REFRESH_TOKEN_EXPIRES:?Variable is not set or empty}

  SMTP_SERVER: ${SMTP_SERVER:?Variable is not set or empty}
  SMTP_PORT: ${SMTP_PORT:?Variable is not set or empty}
  SMTP_USER: ${SMTP_USER:?Variable is not set or empty}
  SMTP_PASSWORD: ${SMTP_PASSWORD:?Variable is not set or empty}
  SMTP_SEND_MAIL_FROM: ${SMTP_SEND_MAIL_FROM}
  SMTP_USE_TLS: ${SMTP_USE_TLS:?Variable is not set or empty}

  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_USER: ${REDIS_USER:?Variable is not set or empty}
  REDIS_PASSWORD: ${REDIS_PASSWORD:?Variable is not set or empty}

  MYSQL_HOST: db
  MYSQL_PORT: 3306
  MYSQL_DATABASE: ${MYSQL_DATABASE:?Variable is not set or empty}
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?Variable is not set or empty}
  MYSQL_USER: ${MYSQL_USER:?Variable is not set or empty}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  S3_ENDPOINT: http://minio:9000
  S3_ACCESS_KEY: ${S3_ACCESS_KEY:?Variable is not set or empty}
  S3_SECRET_KEY: ${S3_SECRET_KEY:?Variable is not set or empty}

  GOTENBERG_ENDPOINT: http://gotenberg:3000

x-celery-environment: &celery-environment
  # app.worker: file/module
  # celery_worker: instance of Celery in file/module
  CELERY_APP: app.worker:celery_worker

services:
  proxy:
    image: nginx:latest
    restart: unless-stopped

  frontend:
    build: ./frontend

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      <<: *backend-environment
    depends_on:
      celery_worker:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      gotenberg:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health" ]
      <<: *default-health-check

  celery_worker:
    build: ./backend
    restart: unless-stopped
    environment:
      <<: [*backend-environment, *celery-environment]
    command: celery worker --loglevel=INFO --concurrency=4
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      gotenberg:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "celery", "inspect", "ping" ]
      <<: *default-health-check

  celery_beat:
    build: ./backend
    restart: unless-stopped
    environment:
      <<: [*backend-environment, *celery-environment]
    command: celery beat --loglevel=INFO
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.45
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:?Variable is not set or empty}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?Variable is not set or empty}
      MYSQL_USER: ${MYSQL_USER:?Variable is not set or empty}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:?Variable is not set or empty}"]
      <<: *default-health-check

  redis:
    image: redis:8.6
    restart: unless-stopped
    environment:
      REDIS_USER: ${REDIS_USER:?Variable is not set or empty}
      REDIS_PASSWORD: ${REDIS_PASSWORD:?Variable is not set or empty}
    command: >
      redis-server
      --user default off
      --user ${REDIS_USER:?Variable is not set or empty} on ">${REDIS_PASSWORD:?Variable is not set or empty}" allcommands allkeys allchannels
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      <<: *default-health-check

  minio:
    image: minio/minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:?Variable is not set or empty}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:?Variable is not set or empty}
    command: server /data --address :9000 --console-address :9001
    healthcheck:
      test: [ "CMD", "curl", "-f",  "http://localhost:9000/minio/health/live" ]
      <<: *default-health-check

  gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      <<: *default-health-check
