services:
  proxy:
    environment:
      FRONTEND_DOMAIN: ${FRONTEND_DOMAIN:?Variable is not set or empty}
      BACKEND_DOMAIN: ${BACKEND_DOMAIN:?Variable is not set or empty}
      MINIO_DOMAIN: ${MINIO_DOMAIN:?Variable is not set or empty}
    volumes:
      - ./docker/nginx/templates/prod.conf.template:/etc/nginx/templates/default.conf.template
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started

  cloudflare:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN:?Variable is not set or empty}

  frontend:
    build:
      context: ./frontend
      target: prod
      args:
        VITE_API_BASE_URL: https://${BACKEND_DOMAIN:?Variable is not set or empty}/api/v1

  backend:
    build:
      context: ./backend
      target: prod
      args:
        UID: ${UID-1000}
        GID: ${GID-1000}
    environment:
      S3_ENDPOINT: https://${MINIO_DOMAIN:?Variable is not set or empty}
      BACKEND_CORS_ORIGINS: >
        "
        http://localhost:8000,
        http://localhost:5173,
        https://${BACKEND_DOMAIN:?Variable is not set or empty},
        https://${FRONTEND_DOMAIN:?Variable is not set or empty},
        "

  celery_worker:
    build:
      context: ./backend
      target: prod
      args:
        UID: ${UID-1000}
        GID: ${GID-1000}
    environment:
      S3_ENDPOINT: https://${MINIO_DOMAIN:?Variable is not set or empty}

  celery_beat:
    build:
      context: ./backend
      target: prod
      args:
        UID: ${UID-1000}
        GID: ${GID-1000}
    environment:
      S3_ENDPOINT: https://${MINIO_DOMAIN:?Variable is not set or empty}

  db:
    volumes:
      - ./docker/backup/mysql/:/var/backup/mysql/
      - db_data_prod:/var/lib/mysql

  redis:
    volumes:
      - redis_data_prod:/data

  minio:
    volumes:
      - minio_data_prod:/data
      - ./docker/backup/minio/:/var/backup/minio/
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:?Variable is not set or empty}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:?Variable is not set or empty}
      MINIO_BROWSER: off
    command: server /data --address :9000

volumes:
  db_data_prod:
  redis_data_prod:
  minio_data_prod: