export const ERROR_CODE = {
    // System
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    SYSTEM_ERROR: "SYSTEM_ERROR",

    // Auth
    UNAUTHORIZED: "UNAUTHORIZED_ERROR",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    USER_IS_IN_ACTIVE: "USER_IS_IN_ACTIVE",
    JWT_TOKEN_EXPIRED: "JWT_TOKEN_EXPIRED",
    JWT_TOKEN_NOT_FRESH: "JWT_TOKEN_NOT_FRESH",
    INVALID_JWT_TOKEN: "INVALID_JWT_TOKEN",
    LOGIN_FAILED: "LOGIN_FAILED",

    // Permission
    FORBIDDEN: "FORBIDDEN",

    // Client
    BAD_REQUEST: "BAD_REQUEST",
    VALIDATION_ERROR: "VALIDATION_ERROR",

    // Resource
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
};