name: Run pytest
on:
  push:
    branches: [master]


jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        run: |
          cp .env.example .env
          mkdir backend/test_reports
          echo "UID=$(id -u)" >> $GITHUB_ENV
          echo "GID=$(id -g)" >> $GITHUB_ENV
          make build
      - run: make test