name: Run pytest
on:
  push:
    branches: [master]


jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - run: cp .env.example .env
      - run: mkdir backend/test_reports
      - run: make build
      - run: make test
  test-backend-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check user
        run: whoami && id

      - name: Get UID/GID
        id: ids
        run: |
          echo "UID=$(id -u)" >> $GITHUB_ENV
          echo "GID=$(id -g)" >> $GITHUB_ENV

      - run: cp .env.example .env

      - run: make build

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - run: cd backend
      - run: uv sync
      - run: uv run pytest